### ISSUE TITLE
modnet_p_ratio_0.5_thresh_0.5.json

### ISSUE THREAD

**Issue by simplew2011** [sisyphus-cv-lab/MODNet-ModelCompression#3]
can you share you modnet_p_ratio_0.5_thresh_0.5.json file.

**Comment by MaitreChen** [comment]
{"ratio":0.5,"threshold":0.5,"new_cfg":[8,8,8,16,24,16,16,48,16,16,8,32,16,32,104,32,64,232,584],"new_expansion_cfg":[1,9,14,4,7,9,3,7,19,22,24,15,30,17,7,26,15],"new_lr_channels":[32,16],"new_hr_channels":[8,16],"new_f_channels":[32]}
